[tool.poetry]
name = "maserol"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
pandas = "^1.4"
scipy = "^1.10"
numpy = "^1.22"
matplotlib = "^3.5.2"
seaborn = ">=0.11.2"
tensordata = {git = "https://github.com/meyer-lab/tensordata.git", branch = "main"}
tqdm = "^4.64.0"
scikit-learn = "^1.1.2"
jax = "^0.3.25"
jaxlib = "^0.3.25"
PyYAML = ">=6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^6.2"
pytest-cov = "^3.0"
mypy = "^0.991"
types-tqdm = "^4.64.7.11"
valentbind = {git = "https://github.com/meyer-lab/valentBind.git", branch = "main"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "maserol.figures.common:genFigure"
