[tool.poetry]
name = "maserol"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pandas = "^1.4"
scipy = "^1.7"
numpy = "^1.22"
tensorly = {git = "https://github.com/tensorly/tensorly.git", branch = "main"}
matplotlib = "^3.5.2"
seaborn = ">=0.11.2"
tensorpack = {git = "https://github.com/meyer-lab/tensorpack.git", branch = "main"}
tensordata = {git = "https://github.com/meyer-lab/tensordata.git", branch = "main"}
tqdm = "^4.64.0"
scikit-learn = "^1.1.2"
jax = "^0.3.24"
jaxlib = "^0.3.24"
PyYAML = ">=6.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-cov = "^3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "maserol.figures.common:genFigure"
