[tool.poetry]
name = "maserol"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pandas = "^1.4"
jaxlib = {url = "https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.3.15+cuda11.cudnn82-cp39-none-manylinux2014_x86_64.whl"}
scipy = "^1.7"
numpy = "^1.22"
jax = "0.3.15"
tensorly = "^0.7"
matplotlib = "3.5.2"
seaborn = "^0.11"
tensorpack = {git = "https://github.com/meyer-lab/tensorpack.git", branch = "main"}
tensordata = {git = "https://github.com/meyer-lab/tensordata.git", branch = "main"}
tqdm = "^4.64.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-cov = "^3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "maserol.figures.common:genFigure"
