from pathlib import Path

import pandas as pd
import seaborn as sns
from tensordata.zohar import data as zohar

from maserol.figures.common import getSetup
from maserol.preprocess import prepare_data

# THIS FIGURE RELIES ON DATA GENERATED BY 3C
THIS_DIR = Path(__file__).parent
CACHE_DIR = THIS_DIR.parent / "data" / "cache"


def makeFigure():
    axes, fig = getSetup((4, 4), (1, 1))
    figure_3c(axes[0])
    return fig


def figure_3c(ax):
    data = prepare_data(zohar())
    data = data.sel(Ligand=[l for l in data.Ligand.values if l != "IgG2"])
    data = data[:500]

    filename = "fig_3c_metrics.csv"
    df = pd.read_csv(CACHE_DIR / filename)

    df = df.replace({"impute_missing_pca": "PCA", "impute_missing_ms": "Binding model"})

    sns.barplot(data=df, x="Ligand", y="r2", hue="Method", ax=ax)
    ax.set_xlabel("Ligand")
    ax.set_ylabel("Imputation Performance (Coefficient of Determination)")
