alter:
  translations:
    rcp:
      FcgRIIa.H131: FcgRIIA-131H
      FcgRIIa.R131: FcgRIIA-131R
      FcgRIIb: FcgRIIB-232I
      FcgRIIIa.F158: FcgRIIIA-158F
      FcgRIIIa.V158: FcgRIIIA-158V
      FcgRIIIb: FcgRIIIB
  include:
    rcp: ["IgG1", "IgG2", "IgG3", "IgG4", "FcgRI", 
          "FcgRIIA-131H", "FcgRIIA-131R", 
          "FcgRIIB-232I", "FcgRIIIA-158F", "FcgRIIIA-158V", 
          "FcgRIIIB", "C1q"]
chung:
  translations:
    rcp:
      FcgR2aH: FcgRIIA-131H
      FcgR2aR: FcgRIIA-131R
      FcgR2b: FcgRIIB-232I
      FcgR3aF: FcgRIIIA-158F
      FcgR3aV: FcgRIIIA-158V